import { Router } from "express";

const router = Router();

const STORES = [
  {
    id: 1,
    owner_id: 1,
    name: "Chifa Felipe Siu",
    description: "Clásico local de San Ramón, el mejor sabor oriental en la selva.",
    email: "felipe.siu@mercanto.pe",
    phone: "964123456",
    address: "Av. Principal 123",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    owner_id: 2,
    name: "Restaurant Turístico Chanchamayo's",
    description: "Especialidad en pescados de río y platos típicos de la selva central.",
    email: "chanchamayos@mercanto.pe",
    phone: "964789012",
    address: "Jr. Leonardo Alvariño 570",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: "/assets/san_ramon_catalog/chicharron_doncella.jpg",
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    owner_id: 3,
    name: "Café Perené & Superfoods",
    description: "Café de altura, miel, polen y productos naturales de Chanchamayo.",
    email: "perene@mercanto.pe",
    phone: "964345678",
    address: "Carretera Central Km 75",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: "/assets/san_ramon_catalog/cafe_chanchamayo_bolsa.jpg",
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    owner_id: 4,
    name: "Minimarket San José",
    description: "Tu tienda de confianza con productos de primera necesidad.",
    email: "sanjose@mercanto.pe",
    phone: "964901234",
    address: "Jr. Lima 456",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    owner_id: 5,
    name: "Fruti Selva",
    description: "Jugos naturales y desayunos típicos con las mejores frutas de la región.",
    email: "frutiselva@mercanto.pe",
    phone: "964567890",
    address: "Jr. Leonardo Alvariño 570",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    owner_id: 6,
    name: "Farmacia Salud Total",
    description: "Atención farmacéutica y productos de salud las 24 horas.",
    email: "saludtotal@mercanto.pe",
    phone: "964111222",
    address: "Av. Principal 789",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 7,
    owner_id: 7,
    name: "Fundo D' Fortuna",
    description: "Productores de café y cacao de especialidad.",
    email: "fortuna@mercanto.pe",
    phone: "964333444",
    address: "Sector Campamento",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: "/assets/san_ramon_catalog/cafe_especialidad.jpg",
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 8,
    owner_id: 8,
    name: "Hogar & Deco San Ramón",
    description: "Muebles y artículos de decoración para tu hogar.",
    email: "hogardeco@mercanto.pe",
    phone: "964555666",
    address: "Jr. Pardo 200",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 9,
    owner_id: 9,
    name: "Ferretería El Tornillo",
    description: "Todo en herramientas y materiales de construcción.",
    email: "eltornillo@mercanto.pe",
    phone: "964777888",
    address: "Av. Marginal 456",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 10,
    owner_id: 10,
    name: "Panadería La Tradición",
    description: "Panes regionales calientitos y pastelería fina.",
    email: "latradicion@mercanto.pe",
    phone: "964999000",
    address: "Jr. Tarma 123",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 11,
    owner_id: 11,
    name: "TJ Estilo & Accesorios",
    description: "Moda, ropa y accesorios para toda la familia.",
    email: "tjestilo@mercanto.pe",
    phone: "964222333",
    address: "Jr. Junín 321",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 12,
    owner_id: 12,
    name: "Vivero Chanchamayo",
    description: "Plantas ornamentales, frutales y abonos orgánicos.",
    email: "vivero@mercanto.pe",
    phone: "964444555",
    address: "Salida a La Merced",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 13,
    owner_id: 13,
    name: "Artesanías Junín",
    description: "Productos hechos a mano por artesanos de la región.",
    email: "artesanias@mercanto.pe",
    phone: "964666777",
    address: "Plaza de Armas",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 14,
    owner_id: 14,
    name: "Parrillada El Fogón",
    description: "Carnes a la parrilla y platos regionales a la leña.",
    email: "elfogon@mercanto.pe",
    phone: "964888999",
    address: "Jr. Libertad 789",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 15,
    owner_id: 15,
    name: "TechStore San Ramón",
    description: "Celulares, laptops y servicio técnico especializado.",
    email: "techstore@mercanto.pe",
    phone: "964000111",
    address: "Av. Principal 555",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 16,
    owner_id: 16,
    name: "La Promisora",
    description: "Mermeladas, néctares y licores de frutas exóticas.",
    email: "promisora@mercanto.pe",
    phone: "964222444",
    address: "Fundo La Promisora",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 17,
    owner_id: 17,
    name: "Botica San Ramón",
    description: "Tu botica de confianza con los mejores precios.",
    email: "boticasr@mercanto.pe",
    phone: "964555111",
    address: "Jr. Lima 123",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 18,
    owner_id: 18,
    name: "Pollos Pío Pío Rico",
    description: "El pollo a la brasa más rico de San Ramón.",
    email: "piopio@mercanto.pe",
    phone: "964777222",
    address: "Jr. Lima 888",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 19,
    owner_id: 19,
    name: "Sublichamo Regalos",
    description: "Regalos personalizados, sublimación y diseño.",
    email: "sublichamo@mercanto.pe",
    phone: "964999333",
    address: "Jr. Pardo 456",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
  {
    id: 20,
    owner_id: 20,
    name: "Licores Selva Central",
    description: "Variedad de licores regionales: Siete Raíces, RC y más.",
    email: "licores@mercanto.pe",
    phone: "964111444",
    address: "Av. Marginal 101",
    city: "San Ramón, Chanchamayo, Junín",
    country: "PE",
    logo_url: null,
    is_active: true,
    status: "approved",
    created_at: new Date().toISOString(),
  },
];

const PRODUCTS: Record<number, any[]> = {
  1: [
    { id: 1, store_id: 1, name: "Arroz Chaufa Especial", description: "Arroz chaufa con pollo, carne y chancho.", price: 18.00, stock: 50, sku: "CHI-001", category: "Chifa", image_url: null, is_active: true, created_at: new Date().toISOString() },
    { id: 2, store_id: 1, name: "Tallarín Saltado de Pollo", description: "Tallarín saltado al estilo oriental.", price: 16.00, stock: 50, sku: "CHI-002", category: "Chifa", image_url: null, is_active: true, created_at: new Date().toISOString() },
  ],
  2: [
    { id: 3, store_id: 2, name: "Tacacho con Cecina", description: "Plato bandera con plátano machacado y cecina ahumada.", price: 25.00, stock: 40, sku: "TYP-001", category: "Comida Típica", image_url: "/assets/san_ramon_catalog/tacacho_cecina.jpg", is_active: true, created_at: new Date().toISOString() },
    { id: 4, store_id: 2, name: "Chicharrón de Doncella", description: "Pescado doncella frito con yucas y salsa de cocona.", price: 28.00, stock: 30, sku: "TYP-002", category: "Comida Típica", image_url: "/assets/san_ramon_catalog/chicharron_doncella.jpg", is_active: true, created_at: new Date().toISOString() },
  ],
  3: [
    { id: 5, store_id: 3, name: "Café Gourmet Chanchamayo 250g", description: "Café tostado y molido de alta calidad.", price: 15.00, stock: 100, sku: "CAF-001", category: "Café", image_url: "/assets/san_ramon_catalog/cafe_chanchamayo_bolsa.jpg", is_active: true, created_at: new Date().toISOString() },
    { id: 6, store_id: 3, name: "Miel de Abeja Pura 1Kg", description: "Miel de flores de la selva central.", price: 35.00, stock: 50, sku: "NAT-001", category: "Naturales", image_url: null, is_active: true, created_at: new Date().toISOString() },
  ],
  7: [
    { id: 7, store_id: 7, name: "Café de Especialidad 500g", description: "Granos seleccionados del Fundo D' Fortuna.", price: 30.00, stock: 60, sku: "CAF-002", category: "Café", image_url: "/assets/san_ramon_catalog/cafe_especialidad.jpg", is_active: true, created_at: new Date().toISOString() },
  ],
  16: [
    { id: 8, store_id: 16, name: "Mermelada de Cocona", description: "Mermelada artesanal de fruta regional.", price: 12.00, stock: 80, sku: "MER-001", category: "Dulces", image_url: null, is_active: true, created_at: new Date().toISOString() },
  ],
  20: [
    { id: 9, store_id: 20, name: "Licor Siete Raíces 750ml", description: "Licor tradicional afrodisíaco de la selva.", price: 45.00, stock: 30, sku: "LIC-001", category: "Licores", image_url: null, is_active: true, created_at: new Date().toISOString() },
  ]
};

// GET /api/stores
router.get("/", (req, res) => {
  const { status, is_active, limit = 20, page = 1 } = req.query;

  let filtered = STORES.filter(s => {
    if (status && s.status !== status) return false;
    if (is_active !== undefined && s.is_active !== (is_active === "true")) return false;
    return true;
  });

  const total = filtered.length;
  const pageNum = parseInt(page as string);
  const limitNum = parseInt(limit as string);
  const paginated = filtered.slice((pageNum - 1) * limitNum, pageNum * limitNum);

  return res.json({
    success: true,
    data: paginated,
    pagination: {
      page: pageNum,
      limit: limitNum,
      total,
      pages: Math.ceil(total / limitNum),
    },
  });
});

// GET /api/stores/:id
router.get("/:id", (req, res) => {
  const store = STORES.find(s => s.id === parseInt(req.params.id));
  if (!store) return res.status(404).json({ success: false, error: "Tienda no encontrada" });
  return res.json({ success: true, data: store });
});

// GET /api/stores/:id/products
router.get("/:id/products", (req, res) => {
  const storeId = parseInt(req.params.id);
  const products = PRODUCTS[storeId] || [];
  return res.json({
    success: true,
    data: products,
    pagination: { page: 1, limit: 50, total: products.length, pages: 1 },
  });
});

export default router;
